apiVersion: platform.confluent.io/v1beta1
kind: Zookeeper
metadata:
  name: zookeeper
  namespace: kb1
spec:
  replicas: 3
  image:
    application: confluentinc/cp-zookeeper:7.4.0
    init: confluentinc/confluent-init-container:2.6.0
  dataVolumeCapacity: 10Gi
  logVolumeCapacity: 10Gi
  podTemplate:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true


---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: kb1
spec:
  replicas: 3
  image:
    application: confluentinc/cp-server:7.5.0
    init: confluentinc/confluent-init-container:2.7.0
  dataVolumeCapacity: 10Gi
  configOverrides:
    server:
      - confluent.cluster.link.enable=true
 # tls:
  #  secretRef: kafka-tls3
  podTemplate:
    serviceAccountName: confluent-sa
    annotations:
      vault.hashicorp.com/agent-inject: "true"
      vault.hashicorp.com/agent-inject-status: update
      vault.hashicorp.com/preserve-secret-case: "true"
      vault.hashicorp.com/agent-init-first: 'true'
      vault.hashicorp.com/agent-inject-secret-plain-jaas.conf: secret/plain-jaas.conf
     # vault.hashicorp.com/secret-volume-path-kafka-sasl-plain: /vault/secrets
     # vault.hashicorp.com/agent-inject-file-kafka-sasl-plain: plain-jaas.conf
      vault.hashicorp.com/agent-inject-template-plain-jaas.conf: |
        {{- with secret "secret/plain-jaas.conf" -}}
        {{ .Data.data.plainjaas | base64Decode }}
        {{- end }}
      vault.hashicorp.com/role: vault-demo      
    resources:
      requests:
        cpu: 200m
        memory: 512Mi
    podSecurityContext:
      fsGroup: 1000
      runAsUser: 1000
      runAsNonRoot: true
      

  listeners:
   # internal:
    #  authentication:
     #   type: mtls
     # tls:
      #  enabled: true
    external:
      authentication:
        type: plain
        jaasConfigPassThrough:
          directoryPathInContainer: /vault/secrets
        #principalMappingRules:
         # - RULE:^.*CN=([a-zA-Z0-9-]*),.*$/$1/L,DEFAULT
         # - RULE:.*CN[\\s]?=[\\s]?([a-zA-Z0-9.]*)?.*/$1/
      tls:
        enabled: false

 # metricReporter:
  #  enabled: true
 # dependencies:
  #  zookeeper:
   #   endpoint: zookeeper.kb.svc.cluster.local:2181

 
  configOverrides:
    server:
      - "confluent.license.topic.replication.factor=3"
      - "confluent.tier.metadata.replication.factor=3"
      - "confluent.metadata.topic.replication.factor=3"
      - "confluent.balancer.topic.replication.factor=3"
      - "confluent.security.event.logger.exporter.kafka.topic.replicas=3"
      - "event.logger.exporter.kafka.topic.replicas=3"
      - "offsets.topic.replication.factor=3"
      - "confluent.cluster.link.enable=true"
      - "password.encoder.secret=secret"

